services:
  - type: web
    name: snippetshare-backend
    env: java
    rootDir: backend
    build:
      javaVersion: 21
    runtime:
      javaVersion: 21
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/SnippetShare-0.0.1-SNAPSHOT.jar"